/*
* non_greedy.frag.cpp
*
* Copyright (c) 2012-2018 Max Muster
* All rights reserved.
*
* Permission to use, copy, modify, and distribute this software for any
* purpose with or without fee is hereby granted, provided that the above
* copyright notice and this permission notice appear in all copies.
*
* THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
* WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
* MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
* ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
* WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
* ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
* OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

#ifndef GEN_NON_GREEDY_HPP_
#define GEN_NON_GREEDY_HPP_

/****************************************************************************
** Autogenerated code for non_greedy.frag
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

static const char* shader_non_greedy_str
    = "/*\n"
      "* non_greedy.frag\n"
      "*\n"
      "* Copyright (c) 2012-2013 Max Muster\n"
      "* All rights reserved.\n"
      "*\n"
      "* Permission to use, copy, modify, and distribute this software for any\n"
      "* purpose with or without fee is hereby granted, provided that the above\n"
      "* copyright notice and this permission notice appear in all copies.\n"
      "*\n"
      "* THE SOFTWARE IS PROVIDED 'AS IS' AND THE AUTHOR DISCLAIMS ALL WARRANTIES\n"
      "* WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF\n"
      "* MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR\n"
      "* ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES\n"
      "* WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN\n"
      "* ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF\n"
      "* OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.\n"
      "*/\n"
      "\n"
      "#version 330\n"
      "\n"
      "\n"
      "";

#endif // GEN_NON_GREEDY_HPP_
